\
\ load so many .afx file to blocks 4500 upward, Screen# 2250 upward
\
    needs load2block
    needs pad"
    needs .pad

    pad" /sfx/zxmsxdemo/aleste_1.afx"             4500 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_10.afx"            4501 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_11.afx"            4502 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_12.afx"            4503 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_13.afx"            4504 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_14.afx"            4505 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_2.afx"             4506 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_3.afx"             4507 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_4.afx"             4508 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_5.afx"             4509 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_6.afx"             4510 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_7.afx"             4511 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_8.afx"             4512 load2block .pad cr 
    pad" /sfx/zxmsxdemo/aleste_9.afx"             4513 load2block .pad cr 
    pad" /sfx/zxmsxdemo/druid_1.afx"              4514 load2block .pad cr 
    pad" /sfx/zxmsxdemo/druid_2.afx"              4515 load2block .pad cr 
    pad" /sfx/zxmsxdemo/druid_3.afx"              4516 load2block .pad cr 
    pad" /sfx/zxmsxdemo/druid_4.afx"              4517 load2block .pad cr 
    pad" /sfx/zxmsxdemo/druid_5.afx"              4518 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_1.afx"           4519 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_10.afx"          4520 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_11.afx"          4521 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_12.afx"          4522 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_13.afx"          4523 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_14.afx"          4524 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_15.afx"          4525 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_16.afx"          4526 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_17.afx"          4527 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_18.afx"          4528 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_19.afx"          4529 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_2.afx"           4530 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_20.afx"          4531 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_21.afx"          4532 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_22.afx"          4533 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_23.afx"          4534 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_24.afx"          4535 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_25.afx"          4536 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_26.afx"          4537 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_3.afx"           4538 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_4.afx"           4539 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_5.afx"           4540 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_6.afx"           4541 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_7.afx"           4542 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_8.afx"           4543 load2block .pad cr 
    pad" /sfx/zxmsxdemo/firebird_9.afx"           4544 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_1.afx"         4545 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_10.afx"        4546 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_11.afx"        4547 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_12.afx"        4548 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_13.afx"        4549 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_14.afx"        4550 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_15.afx"        4551 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_2.afx"         4552 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_3.afx"         4553 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_4.afx"         4554 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_5.afx"         4555 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_6.afx"         4556 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_7.afx"         4557 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_8.afx"         4558 load2block .pad cr 
    pad" /sfx/zxmsxdemo/girlyblock_9.afx"         4559 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_1.afx"          4560 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_10.afx"         4561 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_11.afx"         4562 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_12.afx"         4563 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_13.afx"         4564 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_14.afx"         4565 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_2.afx"          4566 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_3.afx"          4567 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_4.afx"          4568 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_5.afx"          4569 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_6.afx"          4570 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_7.afx"          4571 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_8.afx"          4572 load2block .pad cr 
    pad" /sfx/zxmsxdemo/metalgear_9.afx"          4573 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_1.afx"            4574 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_10.afx"           4575 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_11.afx"           4576 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_12.afx"           4577 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_13.afx"           4578 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_14.afx"           4579 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_15.afx"           4580 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_16.afx"           4581 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_17.afx"           4582 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_18.afx"           4583 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_19.afx"           4584 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_2.afx"            4585 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_20.afx"           4586 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_3.afx"            4587 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_4.afx"            4588 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_5.afx"            4589 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_6.afx"            4590 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_7.afx"            4591 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_8.afx"            4592 load2block .pad cr 
    pad" /sfx/zxmsxdemo/nemesis_9.afx"            4593 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_1.afx"   4594 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_10.afx"  4595 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_11.afx"  4596 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_12.afx"  4597 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_2.afx"   4598 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_3.afx"   4599 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_4.afx"   4600 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_5.afx"   4601 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_6.afx"   4602 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_7.afx"   4603 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_8.afx"   4604 load2block .pad cr 
    pad" /sfx/zxmsxdemo/penguinadventure_9.afx"   4605 load2block .pad cr 
    pad" /sfx/zxmsxdemo/treasureofusas_1.afx"     4606 load2block .pad cr 
    pad" /sfx/zxmsxdemo/treasureofusas_2.afx"     4607 load2block .pad cr 
    pad" /sfx/zxmsxdemo/treasureofusas_3.afx"     4608 load2block .pad cr 
    pad" /sfx/zxmsxdemo/treasureofusas_4.afx"     4609 load2block .pad cr 
    pad" /sfx/zxmsxdemo/treasureofusas_5.afx"     4610 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_1.afx"      4611 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_10.afx"     4612 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_11.afx"     4613 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_12.afx"     4614 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_13.afx"     4615 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_14.afx"     4616 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_15.afx"     4617 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_16.afx"     4618 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_17.afx"     4619 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_18.afx"     4620 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_19.afx"     4621 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_2.afx"      4622 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_20.afx"     4623 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_3.afx"      4624 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_4.afx"      4625 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_5.afx"      4626 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_6.afx"      4627 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_7.afx"      4628 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_8.afx"      4629 load2block .pad cr 
    pad" /sfx/zxmsxdemo/vampirekiller_9.afx"      4630 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_1.afx"              4631 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_10.afx"             4632 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_11.afx"             4633 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_12.afx"             4634 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_2.afx"              4635 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_3.afx"              4636 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_4.afx"              4637 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_5.afx"              4638 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_6.afx"              4639 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_7.afx"              4640 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_8.afx"              4641 load2block .pad cr 
    pad" /sfx/zxmsxdemo/zanac_9.afx"              4642 load2block .pad cr 

