\
\ load so many .afx file to blocks 4402-4495, Screen# 2200 upward
\
needs load2block
needs pad"
needs .pad

pad" tutorial/afx/zxgames/arcanoid2_1.afx"           4402 load2block  .pad cr
pad" tutorial/afx/zxgames/arcanoid2_2.afx"           4403 load2block  .pad cr
pad" tutorial/afx/zxgames/arcanoid2_3.afx"           4404 load2block  .pad cr
pad" tutorial/afx/zxgames/arcanoid2_4.afx"           4405 load2block  .pad cr
pad" tutorial/afx/zxgames/arcanoid2_5.afx"           4406 load2block  .pad cr
pad" tutorial/afx/zxgames/captainfizz_1.afx"         4407 load2block  .pad cr
pad" tutorial/afx/zxgames/captainfizz_2.afx"         4408 load2block  .pad cr
pad" tutorial/afx/zxgames/captainfizz_3.afx"         4409 load2block  .pad cr
pad" tutorial/afx/zxgames/captainfizz_4.afx"         4410 load2block  .pad cr
pad" tutorial/afx/zxgames/captainfizz_5.afx"         4411 load2block  .pad cr
pad" tutorial/afx/zxgames/clickmania_1.afx"          4412 load2block  .pad cr
pad" tutorial/afx/zxgames/clickmania_2.afx"          4413 load2block  .pad cr
pad" tutorial/afx/zxgames/clickmania_3.afx"          4414 load2block  .pad cr
pad" tutorial/afx/zxgames/clickmania_4.afx"          4415 load2block  .pad cr
pad" tutorial/afx/zxgames/clickmania_5.afx"          4416 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_1.afx"           4417 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_10.afx"          4418 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_11.afx"          4419 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_12.afx"          4420 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_2.afx"           4421 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_3.afx"           4422 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_4.afx"           4423 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_5.afx"           4424 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_6.afx"           4425 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_7.afx"           4426 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_8.afx"           4427 load2block  .pad cr
pad" tutorial/afx/zxgames/cybernoid_9.afx"           4428 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_1.afx"              4429 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_2.afx"              4430 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_3.afx"              4431 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_4.afx"              4432 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_5.afx"              4433 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_6.afx"              4434 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_7.afx"              4435 load2block  .pad cr
pad" tutorial/afx/zxgames/exolon_8.afx"              4436 load2block  .pad cr
pad" tutorial/afx/zxgames/fireandice_1.afx"          4437 load2block  .pad cr
pad" tutorial/afx/zxgames/fireandice_2.afx"          4438 load2block  .pad cr
pad" tutorial/afx/zxgames/fireandice_3.afx"          4439 load2block  .pad cr
pad" tutorial/afx/zxgames/fireandice_4.afx"          4440 load2block  .pad cr
pad" tutorial/afx/zxgames/fireandice_5.afx"          4441 load2block  .pad cr
pad" tutorial/afx/zxgames/fireandice_6.afx"          4442 load2block  .pad cr
pad" tutorial/afx/zxgames/licensetokill_1.afx"       4443 load2block  .pad cr
pad" tutorial/afx/zxgames/licensetokill_2.afx"       4444 load2block  .pad cr
pad" tutorial/afx/zxgames/licensetokill_3.afx"       4445 load2block  .pad cr
pad" tutorial/afx/zxgames/licensetokill_4.afx"       4446 load2block  .pad cr
pad" tutorial/afx/zxgames/megatetris2k_1.afx"        4447 load2block  .pad cr
pad" tutorial/afx/zxgames/megatetris2k_2.afx"        4448 load2block  .pad cr
pad" tutorial/afx/zxgames/megatetris2k_3.afx"        4449 load2block  .pad cr
pad" tutorial/afx/zxgames/megatetris2k_4.afx"        4450 load2block  .pad cr
pad" tutorial/afx/zxgames/mineman2_1.afx"            4451 load2block  .pad cr
pad" tutorial/afx/zxgames/mineman2_2.afx"            4452 load2block  .pad cr
pad" tutorial/afx/zxgames/mineman2_3.afx"            4453 load2block  .pad cr
pad" tutorial/afx/zxgames/mineman2_4.afx"            4454 load2block  .pad cr
pad" tutorial/afx/zxgames/mineman2_5.afx"            4455 load2block  .pad cr
pad" tutorial/afx/zxgames/mkdemo_1.afx"              4456 load2block  .pad cr
pad" tutorial/afx/zxgames/mkdemo_2.afx"              4457 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_1.afx"         4458 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_2.afx"         4459 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_3.afx"         4460 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_4.afx"         4461 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_5.afx"         4462 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_6.afx"         4463 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_7.afx"         4464 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_8.afx"         4465 load2block  .pad cr
pad" tutorial/afx/zxgames/netherworld_9.afx"         4466 load2block  .pad cr
pad" tutorial/afx/zxgames/rainbowislands_1.afx"      4467 load2block  .pad cr
pad" tutorial/afx/zxgames/rainbowislands_2.afx"      4468 load2block  .pad cr
pad" tutorial/afx/zxgames/rainbowislands_3.afx"      4469 load2block  .pad cr
pad" tutorial/afx/zxgames/rainbowislands_4.afx"      4470 load2block  .pad cr
pad" tutorial/afx/zxgames/rodland_1.afx"             4471 load2block  .pad cr
pad" tutorial/afx/zxgames/rodland_2.afx"             4472 load2block  .pad cr
pad" tutorial/afx/zxgames/rodland_3.afx"             4473 load2block  .pad cr
pad" tutorial/afx/zxgames/rodland_4.afx"             4474 load2block  .pad cr
pad" tutorial/afx/zxgames/rodland_5.afx"             4475 load2block  .pad cr
pad" tutorial/afx/zxgames/rodland_6.afx"             4476 load2block  .pad cr
pad" tutorial/afx/zxgames/saintdragon_1.afx"         4477 load2block  .pad cr
pad" tutorial/afx/zxgames/saintdragon_2.afx"         4478 load2block  .pad cr
pad" tutorial/afx/zxgames/saintdragon_3.afx"         4479 load2block  .pad cr
pad" tutorial/afx/zxgames/saintdragon_4.afx"         4480 load2block  .pad cr
pad" tutorial/afx/zxgames/silkworm_1.afx"            4481 load2block  .pad cr
pad" tutorial/afx/zxgames/silkworm_2.afx"            4482 load2block  .pad cr
pad" tutorial/afx/zxgames/silkworm_3.afx"            4483 load2block  .pad cr
pad" tutorial/afx/zxgames/silkworm_4.afx"            4484 load2block  .pad cr
pad" tutorial/afx/zxgames/silkworm_5.afx"            4485 load2block  .pad cr
pad" tutorial/afx/zxgames/silkworm_6.afx"            4486 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_1.afx"             4487 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_2.afx"             4488 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_3.afx"             4489 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_4.afx"             4490 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_5.afx"             4491 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_6.afx"             4492 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_7.afx"             4493 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_8.afx"             4494 load2block  .pad cr
pad" tutorial/afx/zxgames/wizball_9.afx"             4495 load2block  .pad cr
